resolver: lts-17.10

# Local packages, usually specified by relative directory name
packages:
- '.'
- ./msgs/Std_msgs
- ./msgs/Std_srvs
- ./msgs/Geometry_msgs
- ./msgs/Sensor_msgs
- ./msgs/Actionlib_msgs
- ./msgs/Nav_msgs
- ./msgs/Turtlesim
- ./Examples/PubSub

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- data-default-generics-0.3
#- storable-tuple-0.0.3.2
#- storable-record-0.0.3.1
# - utility-ht-0.0.12
- uri-0.1.6.4
#- haxr-3000.11.2
#- HaXml-1.25.3

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

nix:
  packages: [openssl, zlib]

# docker:
#   image: roshask
